Edge to edge implementation for starter
google-developer-training/basic-android-kotlin-compose-training-bus-schedule-app pull request #8
Opened 2023-08-15 02:17 UTC by the-scrambler

2023-08-15 17:44 UTC, android-dev-lxl reviewed
Please remove unused val: 
`val seed = Color(0xFF6750A4)
`
Given the min version is 24 so we do not need drawble-V24 folder

BusScheduleViewModel - remove empty construct

`class BusScheduleViewModel(): ViewModel() {` -> `class BusScheduleViewModel: ViewModel() { `

2023-08-15 17:44 UTC, android-dev-lxl commented on app/build.gradle.kts
> +    implementation(platform("androidx.compose:compose-bom:2023.06.01"))
Latest is 2023.08.00

2023-08-15 17:44 UTC, android-dev-lxl commented on app/src/main/java/com/example/busschedule/ui/BusScheduleScreens.kt
> +                ),
This needs to be updated in the main branch as well. 

Could we simplify this code?
.padding(top = contentPadding.calculateTopPadding())

https://github.com/google-developer-training/basic-android-kotlin-compose-training-bus-schedule-app/pull/7#discussion_r1290843497

2023-08-15 17:44 UTC, android-dev-lxl commented on app/src/main/java/com/example/busschedule/ui/BusScheduleScreens.kt
> +            modifier = Modifier.padding(vertical = 8.dp),
Could we use `padding_medium` here.

2023-08-21 16:25 UTC, johnshea requested changes
API 33 details UI is different than API 33 details UI on branch `starter`.

<img width="836" alt="Screenshot 2023-08-21 at 12 22 06 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-bus-schedule-app/assets/7107817/deee5246-53a8-42f5-8b67-15d24db2a411">

2023-08-29 17:49 UTC, johnshea requested changes
There are issue with the UI being noticeably different between branch `starter` and `starter-e2e` that need to be corrected.
- Spacing between the column labels and divider bar (More obvious on portrait mode).
- On landscape e2e, the time is indented further and does not line up with column label.

Note - I added additional stops to confirm nav bar was translucent.

<img width="1172" alt="Screenshot 2023-08-29 at 1 16 10 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-bus-schedule-app/assets/7107817/ae2638f8-da9a-489f-b0c9-a7eae088bd5a">

<img width="1024" alt="Screenshot 2023-08-29 at 1 14 34 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-bus-schedule-app/assets/7107817/a5853de5-8833-40cd-ad7a-325b2f448ae1">




Can build.gradle.kts(app) java version be upgraded to 1.8 for `sourceCompatibility`,`targetCompatibility`, and `jvmTarget`?

2023-09-11 23:30 UTC, closed without merging